export {default as Header} from './Header'
export {default as About} from './About'
export {default as Skill} from './Skill'
export {default as Work} from './Work'
export {default as Link} from './Link'
export {default as Footer} from './Footer'